language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  slack: dadi:pnhiL60xOrm7GOglHUmb7xHK
  email: false
node_js:
  - '8'
  - '10'
  - 'lts/*'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
services:
  - redis-server
