language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - redis-server
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
